function ensemble = generate_ensemble( type, image_size, root_path )

    root_path = [ fullfile( root_path, type ) filesep ];
    if ~isdir( root_path )
        
        mkdir( root_path );
        
    end
    if strcmpi( type, '1L2R' )
        
        ensemble = Ensemble( ...
            root_path, ...
            @one_L_two_R, ...
            image_size, ...
            100, ...
            100, ...
            linspace( 0.1, 0.8, 8 ), ...
            linspace( 0.1, 0.8, 8 ), ...
            1, ...
            0, ...
            [ 0 0 ] ...
            );
        
    end

    if strcmpi( type, '1M2R' )
        
        ensemble = Ensemble( ...
            root_path, ...
            @one_M_two_R, ...
            image_size, ...
            100, ...
            0, ...
            linspace( 0.25, 0.5, 8 ), ...
            linspace( 0.25, 0.5, 8 ), ...
            1, ...
            0, ...
            [ 0 0 ] ...
            );
        
    end

    if strcmpi( type, '3LABAC' )
        
        ensemble = Ensemble( ...
            root_path, ...
            @one_L_two_R, ...
            image_size, ...
            100, ...
            0, ...
            linspace( 0.1, 0.8, 8 ), ...
            linspace( 0.1, 0.8, 8 ), ...
            1, ...
            0, ...
            [ 0 0 ] ...
            );
        
    end

    if strcmpi( type, '3LABC' )
        
        ensemble = Ensemble( ...
            root_path, ...
            @one_L_two_R, ...
            image_size, ...
            100, ...
            0, ...
            linspace( 0.1, 0.8, 8 ), ...
            linspace( 0.1, 0.8, 8 ), ...
            1, ...
            0, ...
            [ 0 0 ] ...
            );
        
    end

    if strcmpi( type, '2L1R' )
        
        ensemble = Ensemble( ...
            root_path, ...
            @one_L_two_R, ...
            image_size, ...
            100, ...
            0, ...
            linspace( 1/6, 2/3, 8 ), ...
            linspace( 1/6, 2/3, 8 ), ...
            1, ...
            0, ...
            [ 0 0 ] ...
            );
        
    end

end

